[package]
name = "raytracer"
version = "0.1.0"
authors = ["Benjamin Thomas (Aviansie Ben) <ben@benthomas.ca>"]

[profile.dev]
panic = "abort"

[profile.release]
debug = true

[dependencies]
cgmath = "0.18.0"
image = "0.23.12"
itertools = "0.10.0"
rayon = "1.5.0"
rand = "0.8.3"
rand_pcg = "0.3.0"
